kind: Service
apiVersion: v1
metadata:
  name: users
spec:
  selector:
    app: users
  ports:
    - port: 4001
  type: ClusterIP

---
kind: Service
apiVersion: v1
metadata:
  name: products
spec:
  selector:
    app: products
  ports:
    - port: 4002
  type: ClusterIP

---
kind: Service
apiVersion: v1
metadata:
  name: carts
spec:
  selector:
    app: carts
  ports:
    - port: 4003
  type: ClusterIP

---
kind: Service
apiVersion: v1
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - port: ku
      nodePort: 30000
  type: NodePort