kind: Deployment
apiVersion: apps/v1
metadata:
  name: carts
spec:
  selector:
    matchLabels:
      app: carts
  replicas: 1
  template:
    metadata:
      labels:
        app: carts
    spec:
      containers:
        - name: carts
          image: gcr.io/kub-demo-337910/cart-service:latest

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: products
spec:
  selector:
    matchLabels:
      app: products
  replicas: 1
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: gcr.io/kub-demo-337910/product-service:latest

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: users
spec:
  selector:
    matchLabels:
      app: users
  replicas: 1
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: gcr.io/kub-demo-337910/user-service:latest

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: gcr.io/kub-demo-337910/gateway-service:latest